# Generated by Django 5.1.6 on 2026-03-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
