# Generated by Django 5.1.6 on 2026-03-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_ledgeraccount_opening_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
