# Generated by Django 5.1.6 on 2026-08-11 14:07

from django.db import migrations, models


def move_archived_contact_numbers(apps, schema_editor):
    LedgerAccount = apps.get_model("ledger", "LedgerAccount")

    for account in LedgerAccount.objects.filter(is_active=False).exclude(contact_number__isnull=True).exclude(contact_number=""):
        if not account.archived_contact_number:
            account.archived_contact_number = account.contact_number
        account.contact_number = None
        account.save(update_fields=["archived_contact_number", "contact_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_ledgerentry_created_by_ledgerentry_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='archived_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(move_archived_contact_numbers, migrations.RunPython.noop),
    ]
