# Generated by Codex on 2026-03-29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"ordering": ["product__name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="purchasebill",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="purchaseitem",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="stockoutlog",
            options={"ordering": ["-used_at"]},
        ),
        migrations.AddField(
            model_name="purchasebill",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchasebill",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("CONFIRMED", "Confirmed")],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchasebill",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
    ]
