# Generated by Django 5.1.6 on 2026-01-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
    ]
