# Generated by Django 5.1.6 on 2026-02-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='quantity',
        ),
        migrations.AddField(
            model_name='menu',
            name='portion_size',
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
    ]
