# Generated by Django 5.1.6 on 2026-03-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menu_quantity_menu_portion_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='portion_size',
        ),
    ]
