# Generated by Django 5.1.6 on 2026-03-04 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_ledgeraccount_opening_balance_and_more'),
        ('orders', '0003_orderitem_customer_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer_account',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ledger.ledgeraccount'),
        ),
    ]
