# Generated by Django 5.1.6 on 2026-03-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_ledgerentry_description'),
        ('orders', '0004_remove_orderitem_customer_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='ledger.ledgeraccount'),
        ),
    ]
