# Generated by Django 5.1.6 on 2026-03-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
