# Generated by Django 5.1.6 on 2026-03-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_guest_count_order_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine In'), ('SCHEDULED_DINE_IN', 'Scheduled Dine In'), ('TAKEAWAY', 'Takeaway'), ('DELIVERY', 'Delivery')], max_length=20),
        ),
    ]
