# Generated by Django 5.1.6 on 2026-03-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cooked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
