# Generated by Django 5.1.6 on 2026-03-27 04:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='online_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online'), ('MIXED', 'Mixed')], max_length=10),
        ),
    ]
