# Generated by Django 5.1.6 on 2026-04-09 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_completed_at_order_cancelled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='acceptance_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='acceptance_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_or_declined_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='acceptance_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='submission_source',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
