# Generated by Django 5.1.6 on 2026-07-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_area_order_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='update_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online'), ('MIXED', 'Mixed'), ('ADVANCE', 'Advance')], max_length=10),
        ),
    ]
