from django.urls import path
from .views import (
    OrderListAPIView,
    OrderDetailAPIView,
    CreateOrderAPIView,
    ActiveOrdersAPIView,
    UpdateOrderAPIView,
    CollectPaymentAPIView,
    ReadyOrderAPIView,
    CompleteOrderAPIView,
    CancelOrderAPIView,
    OrdersFilterAPIView,
    OrderDisplayAPIView,
    StartScheduledOrderAPIView,
    ExternalOrdersAPIView,
    ExternalOrderDecisionAPIView,
    AreaListAPIView,
    CustomerLookupAPIView,
    DeliveryAreaSettingsListCreateAPIView,
    DeliveryAreaSettingsDetailAPIView,
    DeliveryBoySettingsListCreateAPIView,
    DeliveryBoySettingsDetailAPIView,
    BulkCollectOrdersSettingsAPIView,
)

urlpatterns = [

    path("orders/", OrderListAPIView.as_view()),
    path("orders/<int:pk>/", OrderDetailAPIView.as_view()),
    path("orders/create/", CreateOrderAPIView.as_view()),
    path("orders/active/", ActiveOrdersAPIView.as_view()),
    path("orders/<int:pk>/update/", UpdateOrderAPIView.as_view()),
    path("orders/<int:pk>/collect-payment/", CollectPaymentAPIView.as_view()),
    path("orders/<int:pk>/ready/", ReadyOrderAPIView.as_view()),
    path("orders/<int:pk>/complete/", CompleteOrderAPIView.as_view()),
    path("orders/<int:pk>/cancel/", CancelOrderAPIView.as_view()),
    path("orders/external-requests/", ExternalOrdersAPIView.as_view()),
    path("orders/<int:pk>/external-decision/", ExternalOrderDecisionAPIView.as_view()),
    path("orders/filter/", OrdersFilterAPIView.as_view()),
    path("orders/display/", OrderDisplayAPIView.as_view()),
    path("orders/<int:order_id>/start/",StartScheduledOrderAPIView.as_view()),
    path("orders/areas/", AreaListAPIView.as_view()),
    path("orders/customers/", CustomerLookupAPIView.as_view()),
    path("settings/delivery-areas/", DeliveryAreaSettingsListCreateAPIView.as_view()),
    path("settings/delivery-areas/<int:area_id>/", DeliveryAreaSettingsDetailAPIView.as_view()),
    path("settings/delivery-boys/", DeliveryBoySettingsListCreateAPIView.as_view()),
    path("settings/delivery-boys/<int:account_id>/", DeliveryBoySettingsDetailAPIView.as_view()),
    path("settings/collect-orders/", BulkCollectOrdersSettingsAPIView.as_view()),
    

]
